image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
    - build
    - test

build:
  stage: build
  script:
    - 'dotnet restore'  
    - 'dotnet build --no-restore'
  only:
    - master

test:
  stage: test
  script:
    - 'dotnet restore'  
    - 'dotnet test --no-restore'
  only:
    - master