image: mcr.microsoft.com/dotnet/sdk:9.0

workflow: 
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always 

stages:
    - build
    - test
    - build_image

build_source:
  stage: build
  script:
    - 'dotnet restore'  
    - 'dotnet build --no-restore'
  only:
    - master

run_tests:
  stage: test
  script:
    - echo 'hi' 
      
build_catalog_image:
  stage: build_image
  before_script: 
    - cd src/ECommerce.Catalog/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/afshin-imanizadeh/catalog:1.0 .
    - docker push registry.gitlab.com/afshin-imanizadeh/catalog:1.0
      
build_product_management_image:
  stage: build_image
  before_script:
    - cd src/ECommerce.ProductManagement/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/afshin-imanizadeh/product_management:1.0 .
    - docker push registry.gitlab.com/afshin-imanizadeh/product_management:1.0

build_inventory_image:
  stage: build_image
  before_script:
    - cd src/ECommerce.Inventory/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/afshin-imanizadeh/inventory:1.0 .
    - docker push registry.gitlab.com/afshin-imanizadeh/inventory:1.0
